version: '3.8'

services:
  web:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - .:/app
    environment:
      # You can add environment variables here if needed
      # e.g., FLASK_DEBUG=1 for development
      - FLASK_ENV=development